import { collectRenderedAudit } from "@slides-studio/quality/browser";

export function injectStudioBridge(html: string): string {
  const bridge = `<script data-slides-studio-bridge>(function(){
  const qualityAudit=${collectRenderedAudit.toString()};
  const P=1,GRID=8,SNAP=6,MIN_SIZE=16;let mode='browse',selected=null,drag=null,resize=null,canvasScale=1;
  const send=(message)=>parent.postMessage(Object.assign({protocolVersion:P},message),'*');
  const object=(target)=>target&&target.closest?target.closest('[data-object-id]'):null;
  const clear=()=>document.querySelectorAll('[data-studio-selected]').forEach(el=>delete el.dataset.studioSelected);
  const stage=()=>document.querySelector('.deck-stage');
  const stageGeometry=()=>{const el=stage(),active=el?.querySelector('.slide.active,.slide.visible,.slide');return{el,width:el?.offsetWidth||active?.offsetWidth||1920,height:el?.offsetHeight||active?.offsetHeight||1080,rect:el?.getBoundingClientRect()};};
  const overlay=document.createElement('div');overlay.id='slides-studio-selection-overlay';overlay.hidden=true;overlay.innerHTML='<i data-resize-handle="nw"></i><i data-resize-handle="n"></i><i data-resize-handle="ne"></i><i data-resize-handle="e"></i><i data-resize-handle="se"></i><i data-resize-handle="s"></i><i data-resize-handle="sw"></i><i data-resize-handle="w"></i><b data-snap-guide="x"></b><b data-snap-guide="y"></b>';
  const hideGuides=()=>overlay.querySelectorAll('[data-snap-guide]').forEach(el=>el.hidden=true);
  const updateOverlay=(guides=[])=>{if(!selected||!selected.isConnected){overlay.hidden=true;return}const rect=selected.getBoundingClientRect();if(!rect.width||!rect.height){overlay.hidden=true;return}overlay.hidden=false;Object.assign(overlay.style,{left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px'});hideGuides();const geometry=stageGeometry();for(const guide of guides){const line=overlay.querySelector('[data-snap-guide="'+guide.axis+'"]');if(!line||!geometry.rect)continue;line.hidden=false;if(guide.axis==='x'){line.style.left=(geometry.rect.left+guide.value*canvasScale-rect.left)+'px';line.style.top=(-rect.top)+'px';line.style.height=innerHeight+'px'}else{line.style.top=(geometry.rect.top+guide.value*canvasScale-rect.top)+'px';line.style.left=(-rect.left)+'px';line.style.width=innerWidth+'px'}}};
  const select=(el)=>{clear();selected=el;if(el){el.dataset.studioSelected='true';send({type:'studio:select',objectId:el.dataset.objectId,tagName:el.tagName})}else send({type:'studio:select',objectId:null});updateOverlay()};
  const intrinsicRect=(el)=>{const geometry=stageGeometry(),rect=el.getBoundingClientRect(),base=geometry.rect||{left:0,top:0};return{x:(rect.left-base.left)/canvasScale,y:(rect.top-base.top)/canvasScale,width:rect.width/canvasScale,height:rect.height/canvasScale}};
  const siblingsOf=(el)=>Array.from((el.closest('.slide')||document).querySelectorAll('[data-object-id]')).filter(item=>item!==el).map(intrinsicRect);
  const snapRect=(rect,siblings,bypass)=>{if(bypass)return{x:rect.x,y:rect.y,guides:[]};const solve=(axis)=>{const start=axis==='x'?rect.x:rect.y,size=axis==='x'?rect.width:rect.height,candidates=[{delta:Math.round(start/GRID)*GRID-start,guide:{axis,value:Math.round(start/GRID)*GRID,kind:'grid'}}],moving=[start,start+size/2,start+size];for(const sibling of siblings){const siblingStart=axis==='x'?sibling.x:sibling.y,siblingSize=axis==='x'?sibling.width:sibling.height,anchors=[siblingStart,siblingStart+siblingSize/2,siblingStart+siblingSize];moving.forEach((value,mi)=>anchors.forEach((target,si)=>candidates.push({delta:target-value,guide:{axis,value:target,kind:mi===1&&si===1?'center':mi===si?'sibling':'edge'}})))}const priority={center:0,sibling:1,edge:2,grid:3};return candidates.filter(item=>Math.abs(item.delta)<=SNAP).sort((a,b)=>Math.abs(a.delta)-Math.abs(b.delta)||priority[a.guide.kind]-priority[b.guide.kind])[0]};const x=solve('x'),y=solve('y');return{x:rect.x+(x?.delta||0),y:rect.y+(y?.delta||0),guides:[x?.guide,y?.guide].filter(Boolean)}};
  const removeSelected=()=>{if(!selected)return;const objectId=selected.dataset.objectId;selected.remove();selected=null;clear();overlay.hidden=true;send({type:'studio:patch',objectId,patch:{delete:true}});send({type:'studio:select',objectId:null})};
  let qualityFocusTimer=null;const focusQualityIssue=(message)=>{document.querySelector('#slides-studio-quality-focus')?.remove();if(qualityFocusTimer)clearTimeout(qualityFocusTimer);const target=message.objectId?document.querySelector('[data-object-id="'+CSS.escape(message.objectId)+'"]'):null;if(target)select(target);const targetRect=target?.getBoundingClientRect(),bounds=Array.isArray(message.bounds)&&message.bounds.length===4?message.bounds:null,rect=targetRect&&targetRect.width&&targetRect.height?targetRect:bounds?{left:bounds[0],top:bounds[1],width:bounds[2],height:bounds[3]}:null;if(!rect)return;const focus=document.createElement('div');focus.id='slides-studio-quality-focus';Object.assign(focus.style,{left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px'});document.body.append(focus);qualityFocusTimer=setTimeout(()=>focus.remove(),Math.max(500,Math.min(10000,Number(message.durationMs)||2500)))};
  addEventListener('message',(event)=>{const m=event.data||{};if(m.protocolVersion!==P)return;if(m.type==='studio:quality-request'){try{const report=qualityAudit({id:m.requestId,mode:m.mode||'imported',strict:!!m.strict,requireSettled:false,slideIndex:m.slideIndex});send({type:'studio:quality-report',requestId:m.requestId,report})}catch(error){send({type:'studio:quality-report',requestId:m.requestId,report:{schemaVersion:1,id:m.requestId,canvas:{width:stageGeometry().width,height:stageGeometry().height},mode:m.mode||'imported',strict:!!m.strict,issues:[{category:'other',severity:'error',hard:true,reason:String(error),evidence:[]}],passed:false,summary:{total:1,info:0,warning:0,error:1,critical:0,hard:1}}})}return}if(m.type==='studio:quality-focus'){focusQualityIssue(m);return}if(m.type==='studio:set-mode'){mode=m.mode;document.documentElement.dataset.studioMode=mode;document.querySelectorAll('[contenteditable=true]').forEach(el=>el.removeAttribute('contenteditable'));if(mode==='browse')select(null)}if(m.type==='studio:go-to'){document.querySelectorAll('.slide').forEach((el,i)=>{el.classList.toggle('active',i===m.index);el.classList.toggle('visible',i===m.index)});select(null)}if(m.type==='studio:delete-selected')removeSelected();if(m.type==='studio:nudge-selected'&&selected){const tx=parseFloat(selected.dataset.tx||'0')+m.dx,ty=parseFloat(selected.dataset.ty||'0')+m.dy;selected.dataset.tx=String(tx);selected.dataset.ty=String(ty);selected.style.translate=tx+'px '+ty+'px';updateOverlay();send({type:'studio:patch',objectId:selected.dataset.objectId,patch:{style:{translate:selected.style.translate}}})}if(m.type==='studio:patch'){const el=document.querySelector('[data-object-id="'+CSS.escape(m.objectId)+'"]');if(!el)return;const p=m.patch||{};if(p.delete===true){el.remove();if(selected===el)select(null);return}if(typeof p.text==='string')el.textContent=p.text;if(p.style&&typeof p.style==='object')Object.assign(el.style,p.style);if(p.attributes&&typeof p.attributes==='object')Object.entries(p.attributes).forEach(([name,value])=>value==null?el.removeAttribute(name):el.setAttribute(name,String(value)));updateOverlay()}});
  addEventListener('click',(event)=>{if(mode==='browse'||event.target.closest?.('#slides-studio-selection-overlay'))return;const el=object(event.target);if(!el)return;event.preventDefault();event.stopPropagation();select(el);if(mode==='edit'&&!['IMG','VIDEO','SVG'].includes(el.tagName))el.setAttribute('contenteditable','true')},true);
  addEventListener('input',(event)=>{const el=object(event.target);if(el)send({type:'studio:patch',objectId:el.dataset.objectId,patch:{text:el.textContent||''}})},true);
  addEventListener('pointerdown',(event)=>{if(mode!=='move'||event.target.closest?.('#slides-studio-selection-overlay'))return;const el=object(event.target);if(!el)return;event.preventDefault();event.stopPropagation();select(el);const rect=intrinsicRect(el);drag={el,x:event.clientX,y:event.clientY,tx:parseFloat(el.dataset.tx||'0'),ty:parseFloat(el.dataset.ty||'0'),rect,siblings:siblingsOf(el)};el.setPointerCapture?.(event.pointerId)},true);
  overlay.addEventListener('pointerdown',(event)=>{const handle=event.target.closest('[data-resize-handle]');if(!handle||!selected||mode!=='move')return;event.preventDefault();event.stopPropagation();const rect=intrinsicRect(selected);resize={el:selected,dir:handle.dataset.resizeHandle,x:event.clientX,y:event.clientY,width:rect.width,height:rect.height,tx:parseFloat(selected.dataset.tx||'0'),ty:parseFloat(selected.dataset.ty||'0')};handle.setPointerCapture?.(event.pointerId)},true);
  addEventListener('pointermove',(event)=>{if(drag){const desired={x:drag.rect.x+(event.clientX-drag.x)/canvasScale,y:drag.rect.y+(event.clientY-drag.y)/canvasScale,width:drag.rect.width,height:drag.rect.height},snapped=snapRect(desired,drag.siblings,event.altKey),tx=drag.tx+snapped.x-drag.rect.x,ty=drag.ty+snapped.y-drag.rect.y;drag.el.dataset.tx=String(tx);drag.el.dataset.ty=String(ty);drag.el.style.translate=tx+'px '+ty+'px';updateOverlay(snapped.guides)}if(resize){const dx=(event.clientX-resize.x)/canvasScale,dy=(event.clientY-resize.y)/canvasScale,west=resize.dir.includes('w'),east=resize.dir.includes('e'),north=resize.dir.includes('n'),south=resize.dir.includes('s');let width=Math.max(MIN_SIZE,resize.width+(east?dx:west?-dx:0)),height=Math.max(MIN_SIZE,resize.height+(south?dy:north?-dy:0));if(!event.altKey){width=Math.max(MIN_SIZE,Math.round(width/GRID)*GRID);height=Math.max(MIN_SIZE,Math.round(height/GRID)*GRID)}const tx=resize.tx+(west?resize.width-width:0),ty=resize.ty+(north?resize.height-height:0);resize.el.dataset.tx=String(tx);resize.el.dataset.ty=String(ty);Object.assign(resize.el.style,{width:width+'px',height:height+'px',translate:tx+'px '+ty+'px'});updateOverlay()}},true);
  addEventListener('pointerup',()=>{if(drag){hideGuides();send({type:'studio:patch',objectId:drag.el.dataset.objectId,patch:{style:{translate:drag.el.style.translate}}});drag=null}if(resize){send({type:'studio:patch',objectId:resize.el.dataset.objectId,patch:{style:{width:resize.el.style.width,height:resize.el.style.height,translate:resize.el.style.translate}}});resize=null}},true);
  addEventListener('keydown',(event)=>{if(!selected||event.target.closest?.('input,textarea,[contenteditable=true]'))return;if((event.key==='Delete'||event.key==='Backspace')){event.preventDefault();removeSelected();return}if(mode==='move'&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();const step=event.shiftKey?10:1,tx=parseFloat(selected.dataset.tx||'0')+(event.key==='ArrowLeft'?-step:event.key==='ArrowRight'?step:0),ty=parseFloat(selected.dataset.ty||'0')+(event.key==='ArrowUp'?-step:event.key==='ArrowDown'?step:0);selected.dataset.tx=String(tx);selected.dataset.ty=String(ty);selected.style.translate=tx+'px '+ty+'px';updateOverlay();send({type:'studio:patch',objectId:selected.dataset.objectId,patch:{style:{translate:selected.style.translate}}})}},true);
  const style=document.createElement('style');style.textContent='[data-studio-selected]{outline:2px solid #f05a36!important;outline-offset:3px}[data-studio-mode="move"] [data-object-id]{cursor:grab}[data-studio-mode="edit"] [data-object-id]{cursor:text}#slides-studio-selection-overlay{position:fixed;z-index:2147483647;pointer-events:none;border:1px solid #f05a36}#slides-studio-selection-overlay>i{position:absolute;width:10px;height:10px;border:2px solid white;background:#f05a36;pointer-events:auto}#slides-studio-selection-overlay>[data-resize-handle="nw"]{left:-6px;top:-6px;cursor:nwse-resize}#slides-studio-selection-overlay>[data-resize-handle="n"]{left:calc(50% - 5px);top:-6px;cursor:ns-resize}#slides-studio-selection-overlay>[data-resize-handle="ne"]{right:-6px;top:-6px;cursor:nesw-resize}#slides-studio-selection-overlay>[data-resize-handle="e"]{right:-6px;top:calc(50% - 5px);cursor:ew-resize}#slides-studio-selection-overlay>[data-resize-handle="se"]{right:-6px;bottom:-6px;cursor:nwse-resize}#slides-studio-selection-overlay>[data-resize-handle="s"]{left:calc(50% - 5px);bottom:-6px;cursor:ns-resize}#slides-studio-selection-overlay>[data-resize-handle="sw"]{left:-6px;bottom:-6px;cursor:nesw-resize}#slides-studio-selection-overlay>[data-resize-handle="w"]{left:-6px;top:calc(50% - 5px);cursor:ew-resize}#slides-studio-selection-overlay>b{position:absolute;display:block;background:#36a3f0;pointer-events:none}#slides-studio-selection-overlay>[data-snap-guide="x"]{width:1px}#slides-studio-selection-overlay>[data-snap-guide="y"]{height:1px}#slides-studio-quality-focus{position:fixed;z-index:2147483646;pointer-events:none;border:3px solid #ffb000;background:#ffb00018;box-shadow:0 0 0 4px #fff8,0 0 0 7px #ffb00055;animation:slides-studio-quality-pulse .8s ease-in-out infinite alternate}@keyframes slides-studio-quality-pulse{to{box-shadow:0 0 0 7px #fff8,0 0 0 11px #ffb00022}}';document.head.append(style);document.body.append(overlay);
  const fit=()=>{const geometry=stageGeometry();if(!geometry.el)return;canvasScale=Math.min(innerWidth/geometry.width,innerHeight/geometry.height);Object.assign(geometry.el.style,{position:'absolute',transformOrigin:'0 0',transform:'scale('+canvasScale+')',left:((innerWidth-geometry.width*canvasScale)/2)+'px',top:((innerHeight-geometry.height*canvasScale)/2)+'px'});updateOverlay()};addEventListener('resize',fit);fit();
  send({type:'studio:ready'});
})();</script>`;
  return /<\/body>/i.test(html) ? html.replace(/<\/body>/i, () => `${bridge}</body>`) : `${html}${bridge}`;
}
